### ISSUE TITLE
libcrypto.so.3 broken tentacle updates

### ISSUE THREAD

**Issue by tivanov-qb** [OctopusDeploy/OctopusTentacle#1023]
### Team

- [X] I've assigned a team label to this issue

### What happened?

this PR: https://github.com/OctopusDeploy/OctopusTentacle/pull/1021/files has caused issues while trying to update tentacle package to latest version using yum update for example

### Reproduction

try running yum update with having Package tentacle.x86_64 0:8.2.2297-1 
or try installing latest tentacle package

Error: Package: tentacle-8.2.2319-1.x86_64 (tentacle)
           Requires: libcrypto.so.3()(64bit)

### Workaround

using --skip-broken

**Comment by tivanov-qb** [comment]
@benPearce1

**Comment by tivanov-qb** [comment]
@benPearce1 i see there is a workaround, but i hope there would be "final fix" implemented ?

**Comment by benPearce1** [comment]
@tivanov-qb thanks for letting me know. I will take a look at this as soon as possible.

**Comment by benPearce1** [comment]
@tivanov-qb I have confirmed that this is broken on Amazon Linux 2, which only provides `libcrypto.so.10()(64bit)` out of the box.

**Comment by tivanov-qb** [comment]
@benPearce1 is there a plan to fix this or workaround needs to be used ?

**Comment by benPearce1** [comment]
@tivanov-qb Yes there will be a fix for it. 
There are two possible solutions I am investigating, [boolean operators](https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html) and [macros](https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto#Handling_dependencies). 

The boolean operators require RPM 4.13, Amazon Linux 2 only has 4.11 installed out of the box. 

The macro solution is awkward to implement because we are currently using [fpm](https://github.com/OctopusDeploy/OctopusTentacle/blob/main/linux-packages/packaging-scripts/package.sh#L54) to build the RPM and DEB packages and it doesn't support macros directly.

**Comment by benPearce1** [comment]
@tivanov-qb I have rolled back the change which will fix this, available in version `8.2.2337`

**Comment by tivanov-qb** [comment]
thank you, Ben
